module.exports = {
  css:         require('./lib/formats/css'),
  defaults:    require('./lib/formats/defaults'),
  gnome:       require('./lib/formats/gnome'),
  guake:       require('./lib/formats/guake'),
  iterm:       require('./lib/formats/iterm'),
  konsole:     require('./lib/formats/konsole'),
  mintty:      require('./lib/formats/mintty'),
  putty :      require('./lib/formats/putty'),
  termite:     require('./lib/formats/termite'),
  terminator:  require('./lib/formats/terminator'),
  url:         require('./lib/formats/url'),
  xfce:        require('./lib/formats/xfce'),
  xresources:  require('./lib/formats/xresources'),
};
