'use strict';

module.exports = {
  export:       require('./exporter'),
  alacritty:    require('./formats/alacritty'),
  chromeshell:  require('./formats/chrome-secure-shell'),
  defaults:     require('./formats/defaults'),
  gnome:        require('./formats/gnome'),
  guake:        require('./formats/guake'),
  iterm:        require('./formats/iterm'),
  json:         require('./formats/json'),
  konsole:      require('./formats/konsole'),
  linux:        require('./formats/linux'),
  mintty:       require('./formats/mintty'),
  putty :       require('./formats/putty'),
  st :          require('./formats/st'),
  terminalapp:  require('./formats/terminal-app'),
  terminator:   require('./formats/terminator'),
  termite:      require('./formats/termite'),
  text:         require('./formats/text'),
  textmate:     require('./formats/textmate'),
  xfce:         require('./formats/xfce'),
  xresources:   require('./formats/xresources'),
  xshell:       require('./formats/xshell'),
};
